---
- name: Add Tor repository [ 1 / 2 ]
  become: true
  become_method: sudo
  apt_repository:
    repo: deb http://deb.torproject.org/torproject.org {{ distribution }} main
    state: present
    update_cache: false

- name: Add Tor repository [ 2 / 2 ]
  become: true
  become_method: sudo
  apt_repository:
    repo: deb-src http://deb.torproject.org/torproject.org {{ distribution }} main
    state: present
    update_cache: false

- name: Add gpg key used to sign packages
  become: true
  become_method: sudo
  command: "gpg --keyserver keys.gnupg.net --recv A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89"

- name: Add gpg key used to sign packages
  become: true
  become_method: sudo
  command: "gpg --export A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89 | sudo apt-key add -"

- name: Install Tor and Tor Keyring packages
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: true
  with_items: ["deb.torproject.org-keyring", "tor"]

# These lines will have to be configured in the /etc/tor/torrc file:
# 
# TransPort 192.168.56.1:9040
# DNSPort 192.168.56.1:5353

- name: Enable and restart Tor service
  become: true
  become_method: sudo
  service:
    name: tor
    state: restarted
    enabled: true
