---
- name: Check that the Moloch deb package exists
  stat:
    path: /tmp/moloch_{{ moloch_ver }}_amd64.deb
  register: moloch_deb_package_file

- name: Download Moloch deb package
  become: true
  become_method: sudo
  get_url: url=https://files.molo.ch/builds/ubuntu-18.04/moloch_{{ moloch_ver }}_amd64.deb dest=/tmp mode=0644
  when: moloch_deb_package_file.stat.exists == false

- name: Install Moloch [ 1 / 3 ]
  become: true
  become_method: sudo
  shell: "dpkg -i /tmp/moloch_{{ moloch_ver }}_amd64.deb"
  register: install_moloch_result
  ignore_errors: true

- name: Install Moloch [ 2 / 3 ]
  become: true
  become_method: sudo
  shell: "apt install -f"
  when: "'error' in install_moloch_result.stderr"

- name: Install Moloch [ 3 / 3 ]
  become: true
  become_method: sudo
  shell: "dpkg -i /tmp/moloch_{{ moloch_ver }}_amd64.deb"
  when: "'error' in install_moloch_result.stderr"

- name: Backing up old Configure file
  become: true
  become_method: sudo
  command: mv /data/moloch/bin/Configure /data/moloch/bin/Configure.original

##########################################
# This section is copied from
# https://github.com/ReconInfoSec/ansible-moloch
# with slight modifications
- name: Copy patched Configuration script to server
  become: true
  become_method: sudo
  copy:
    src: "{{ item }}"
    dest: "/data/moloch/bin"
    owner: "root"
    group: "root"
    mode: 0755
  with_fileglob:
    - ../files/Configure

- name: Run configuration script
  become: true
  become_method: sudo
  shell: "/data/moloch/bin/Configure"
  environment:
    MOLOCH_INTERFACE: "{{ ananic }}"
    MOLOCH_LOCALELASTICSEARCH: "no"
    MOLOCH_ELASTICSEARCH: "http://localhost:9200"
    MOLOCH_PASSWORD: "{{ cuckoo_user }}"
    MOLOCH_INET: "yes"
# End of section
##########################################

- name: Configure Moloch initialization
  become: true
  become_method: sudo
  shell: "/data/moloch/db/db.pl http://localhost:9200 init"

- name: Configure Moloch user
  become: true
  become_method: sudo
  shell: "/data/moloch/bin/moloch_add_user.sh cuckoo cuckoo cuckoo --admin"

- name: Ensuring right permissions is set to moloch/bin
  become: true
  become_method: sudo
  file:
    path: /data/moloch/bin
    state: directory
    owner: "nobody"
    group: "daemon"
    mode: 0775

- name: Ensuring right permissions is set to moloch/raw
  become: true
  become_method: sudo
  file:
    path: /data/moloch/raw
    state: directory
    owner: "nobody"
    group: "daemon"
    mode: 0775

- name: Removing old systemd file [ 1 / 2 ]
  become: true
  become_method: sudo
  command: rm /etc/systemd/system/molochviewer.service

- name: Removing old systemd file [ 2 / 2 ]
  become: true
  become_method: sudo
  command: rm /etc/systemd/system/molochcapture.service

- name: Copy local Molochservices files to server [ 1 / 2 ]
  become: true
  become_method: sudo
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/"
    owner: "root"
    group: "root"
    mode: 0644
  with_fileglob:
    - ../files/molochcapture.service

- name: Copy local Molochservices files to server [ 2 / 2 ]
  become: true
  become_method: sudo
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/"
    owner: "root"
    group: "root"
    mode: 0644
  with_fileglob:
    - ../files/molochviewer.service

- name: Reloading systemd to reflect changes
  become: true
  become_method: sudo
  command: systemctl daemon-reload

- name: Enable and start Moloch capture service
  become: true
  become_method: sudo
  service:
    name: molochcapture
    state: started
    enabled: yes

- name: Enable and restart Moloch viewer service
  become: true
  become_method: sudo
  service:
    name: molochviewer
    state: started
    enabled: yes
