---
- name: Enable IPv4 forward [ 1 / 2 ]
  become: true
  become_method: sudo
  command: "echo 1 | sudo tee -a /proc/sys/net/ipv4/ip_forward"

- name: Enable IPv4 forward [ 2 / 2 ]
  become: true
  become_method: sudo
  command: "sysctl -w net.ipv4.ip_forward=1"

- name: Add Iptables rule [ 1 / 3 ]
  become: true
  become_method: sudo
  command: "iptables -A FORWARD -i {{ ananic }} -o {{ nic }} -j ACCEPT"

- name: Add Iptables rule [ 2 / 3 ]
  become: true
  become_method: sudo
  command: "iptables -A FORWARD -i {{ ananic }} -o {{ nic }} -m state --state RELATED,ESTABLISHED -j ACCEPT"

- name: Add Iptables rule [ 3 / 3 ]
  become: true
  become_method: sudo
  command: "iptables -A POSTROUTING -t nat -o {{ nic }} -j MASQUERADE"

- name: Allowing Iptables rules to be persistent between reboots
  become: true
  become_method: sudo
  command: "netfilter-persistent save"
