---
- name: Enable IPv4 forward
  become: true
  become_method: sudo
  command: "sysctl -w net.ipv4.ip_forward=1"

- name: Add Iptables rule [ 1 / 3 ]
  become: true
  become_method: sudo
  command: "iptables -A FORWARD -s 192.168.56.0/24 -j ACCEPT"

- name: Add Iptables rule [ 2 / 3 ]
  become: true
  become_method: sudo
  command: "iptables -A FORWARD -s 192.168.57.0/24 -j ACCEPT"

- name: Add Iptables rule [ 3 / 3 ]
  become: true
  become_method: sudo
  command: "iptables -A POSTROUTING -t nat -o enp2s0 -j MASQUERADE"