---
- name: Backup rt_tables file
  become: true
  become_method: sudo
  command: cp /etc/iproute2/rt_tables /etc/iproute2/rt_tables.original

- name: Copy local rt_tables file to /etc/iproute2
  become: true
  become_method: sudo
  copy:
    src: "{{ item }}"
    dest: "/etc/iproute2/"
    owner: "root"
    group: "root"
    mode: 0644
  with_fileglob:
    - ../files/rt_tables

- name: Copy local openvpn configuration file to /etc/openvpn/client
  become: true
  become_method: sudo
  copy:
    src: "{{ item }}"
    dest: "/etc/openvpn/client/"
    owner: "root"
    group: "root"
    mode: 0700
  with_fileglob:
    - ../files/openvpn.conf

- name: Copy local route.py file to /etc/openvpn/client
  become: true
  become_method: sudo
  copy:
    src: "{{ item }}"
    dest: "/etc/openvpn/client/"
    owner: "root"
    group: "root"
    mode: 0700
  with_fileglob:
    - ../files/route.py

- name: Copy local openvpnclient.service to /etc/systemd/system/
  become: true
  become_method: sudo
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/"
    owner: "root"
    group: "root"
    mode: 0644
  with_fileglob:
    - ../files/openvpnclient.service

- name: Enable and start openvpnclient.service
  become: true
  become_method: sudo
  systemd:
    name: openvpnclient
    state: started
    enabled: yes
