---
- name: Check if "{{ cuckoo_user }}" user exists
  become: true
  become_method: sudo
  shell: "id -u {{ cuckoo_user }}"
  register: user_exists
  failed_when: user_exists.rc != 1

- name: Create "{{ cuckoo_user }}" group
  become: true
  become_method: sudo
  group:
    name: "{{ cuckoo_user }}"
    state: present
  when: '"id" in user_exists.stdout'

- name: Create "{{ cuckoo_user }}" user
  become: true
  become_method: sudo
  user:
    name: "{{ cuckoo_user }}"
    state: present
    group: "{{ cuckoo_user }}"
    groups: sudo,{{ cuckoo_user }}
    shell: /bin/bash
    home: "/home/{{ cuckoo_user }}"
  when: '"id" in user_exists.stdout'

- name: Allow "{{ cuckoo_user }}" group to have passwordless sudo
  become: yes
  become_method: sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%{{ cuckoo_user }}"
    line: "%{{ cuckoo_user }} ALL=(ALL) NOPASSWD: ALL"
    validate: visudo -cf %s
  when: '"id" in user_exists.stdout'

- name: Ensures /home/{{ cuckoo_user }} dir exists
  become: true
  become_method: sudo
  file:
    path: "/home/{{ cuckoo_user }}"
    state: directory
    owner: "{{ cuckoo_user }}"
    group: "{{ cuckoo_user }}"
  when: '"id" in user_exists.stdout'