# run [ ansible-playbook -i inventories/staging site.yml ] for local  setup
# run [ ansible-playbook -i inventories/production site.yml ] for remote setup
---
- hosts: all
  gather_facts: false
  roles:
   - python
   - cuckoo_user
   - build_directory
   - ubuntu_packages
   - python_packages
   - postgresql
   - elasticsearch
   - cuckoo
   - yara
   - volatility
   - suricata
   - moloch
   - tor
   - inetsim
   - openvpn
   - network
   - start_up_cuckoo
