---
- name: Add Suricata PPA repository
  become: true
  become_method: sudo
  apt_repository:
    repo: ppa:oisf/suricata-stable
    state: present
    update_cache: false

- name: Install Suricata
  become: true
  become_method: sudo
  apt:
    name: suricata
    state: latest
    update_cache: true

- name: Install oinkmaster
  become: true
  become_method: sudo
  apt:
    pkg: oinkmaster
    state: present
    update_cache: false

- name: Ensures /var/log/suricata dir exists
  become: true
  become_method: sudo
  file:
    path: /var/log/suricata
    state: directory

- name: Change owner of /var/log/suricata folder
  become: true
  become_method: sudo
  file:
    path: "/var/log/suricata"
    state: directory
    recurse: true
    owner: "{{ cuckoo_user }}"
    group: "{{ cuckoo_user }}"
    mode: 0775

- name: Change owner of /etc/suricata folder
  become: true
  become_method: sudo
  file:
    path: "/etc/suricata"
    state: directory
    recurse: true
    owner: "{{ cuckoo_user }}"
    group: "{{ cuckoo_user }}"
    mode: 0775

- name: Ensures /var/run/suricata dir exists
  become: true
  become_method: sudo
  file:
    path: /var/run/suricata
    state: directory

- name: Change owner of /var/run/suricata folder
  become: true
  become_method: sudo
  file:
    path: "/var/run/suricata"
    state: directory
    recurse: true
    owner: "{{ cuckoo_user }}"
    group: "{{ cuckoo_user }}"
    mode: 0775

- name: Backup suricata.yaml file
  become: true
  become_method: sudo
  become_user: "{{ cuckoo_user }}"
  command: cp /etc/suricata/suricata.yaml /etc/suricata/suricata.yaml.original

- name: Copy local suricata.yaml to /etc/suricata
  become: true
  become_method: sudo
  become_user: "{{ cuckoo_user }}"
  copy:
    src: "{{ item }}"
    dest: "/etc/suricata"
    owner: "{{ cuckoo_user }}"
    group: "{{ cuckoo_user }}"
    mode: 0644
  with_fileglob:
    - ../files/suricata.yaml

- name: Copy local suricata.log to /etc/suricata
  become: true
  become_method: sudo
  become_user: "{{ cuckoo_user }}"
  copy:
    src: "{{ item }}"
    dest: "/etc/suricata"
    owner: "{{ cuckoo_user }}"
    group: "{{ cuckoo_user }}"
    mode: 0644
  with_fileglob:
    - ../files/suricata.log

- name: Backup oinkmaster.conf file
  become: true
  become_method: sudo
  command: mv /etc/oinkmaster.conf /etc/oinkmaster.conf.original

- name: Copy local oinkmaster.conf to /etc
  become: true
  become_method: sudo
  copy:
    src: "{{ item }}"
    dest: "/etc"
    owner: "{{ cuckoo_user }}"
    group: "{{ cuckoo_user }}"
    mode: 0644
  with_fileglob:
    - ../files/oinkmaster.conf

- name: Ensures /etc/emergingthreats/rules dir exists
  become: true
  become_method: sudo
  file:
    path: /etc/emergingthreats/rules
    state: directory
    owner: "{{ cuckoo_user }}"
    group: "{{ cuckoo_user }}"
    mode: 0775

- name: Extract emergingthreats rules
  become: true
  become_method: sudo
  become_user: "{{ cuckoo_user }}"
  shell: oinkmaster -u http://rules.emergingthreats.net/open/suricata/emerging.rules.tar.gz -o /etc/emergingthreats/rules

- name: Find emergingthreats rules
  become: true
  become_method: sudo
  become_user: "{{ cuckoo_user }}"
  find:
    paths: /etc/emergingthreats/rules
    patterns: '*'
    recurse: false
  register: emergingthreats_files

- name: Create link to emergingthreats rules
  become: true
  become_method: sudo
  become_user: "{{ cuckoo_user }}"
  file:
    src: /etc/emergingthreats/rules/{{ item }}
    dest: /etc/suricata/rules/{{ item }}
    state: link
    force: true
  with_items: "{{ emergingthreats_files }}"

- name: Set crontab to update Suricata emergingthreats rules
  become: true
  become_method: sudo
  become_user: "{{ cuckoo_user }}"
  cron:
    name: "Update Suricata rules"
    minute: "0"
    hour: "0"
    day: "*"
    month: "*"
    weekday: "*"
    job: "oinkmaster -u http://rules.emergingthreats.net/open/suricata/emerging.rules.tar.gz -o /etc/emergingthreats/rules"

- name: Stopping Suricata.service
  become: true
  become_method: sudo
  systemd:
    state: stopped
    name: suricata.service

- name: Backing up /etc/default/suricata
  become: true
  become_method: sudo
  command: cp /etc/default/suricata /etc/default/suricata.original

- name: Copy local /etc/default/suricata to server
  become: true
  become_method: sudo
  copy:
    src: "{{ item }}"
    dest: "/etc/default"
    owner: "root"
    group: "root"
    mode: 0644
  with_fileglob:
    - ../files/suricata

- name: Starting Suricata.service to reload new config
  become: true
  become_method: sudo
  systemd:
    state: started
    name: suricata.service
